# Generated by Django 3.1.4 on 2021-01-06 12:17

import core.extra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_function_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=core.extra.upload_image),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='admin_app.Skill'),
        ),
    ]
