# Generated by Django 3.1.4 on 2021-01-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='functions',
            field=models.ManyToManyField(blank=True, to='admin_app.Function'),
        ),
    ]
