# Generated by Django 3.1.4 on 2021-02-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_auto_20210211_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdown',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
