# Generated by Django 3.1.4 on 2021-02-11 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_dropdown_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='read_notifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), blank=True, default=list, size=None),
        ),
    ]
