# Generated by Django 3.1.4 on 2021-02-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_adminuser_read_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='active_projects',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
