# Generated by Django 3.1.4 on 2021-07-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_auto_20210708_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='android_release_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appversion',
            name='ios_release_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
