# Generated by Django 3.1.4 on 2021-09-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_auto_20210708_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('tag_name',)},
        ),
        migrations.AlterModelOptions(
            name='dropdown',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('tag_name',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('tag_name',)},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='skill',
            name='tag_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
