# Generated by Django 3.1.4 on 2023-07-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_auto_20210929_0724'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX idx_skill_tag_name ON admin_app_skill (tag_name);",
            "DROP INDEX idx_skill_tag_name;",
        ),
         migrations.RunSQL(
            "CREATE INDEX idx_role_tag_name ON admin_app_role (tag_name);",
            "DROP INDEX idx_role_tag_name;",
        ),
    ]
