# Generated by Django 3.1.4 on 2021-01-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0013_auto_20210119_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=200)),
                ('zoho_id', models.CharField(max_length=100)),
                ('bd_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('role_type', models.CharField(max_length=20)),
                ('model_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('flex_details', models.CharField(max_length=60)),
                ('stage', models.CharField(max_length=30)),
                ('status_description', models.TextField(blank=True)),
                ('next_step', models.TextField(blank=True)),
                ('post_status', models.CharField(blank=True, max_length=60)),
                ('project_created', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.adminuser')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.function')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.role')),
            ],
        ),
    ]
