# Generated by Django 3.1.4 on 2021-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210127_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexidetails',
            name='project_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flexidetails',
            name='turn_around_time',
            field=models.IntegerField(null=True),
        ),
    ]
