# Generated by Django 3.1.4 on 2021-01-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210127_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='max_total_experience_needed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='min_total_experience_needed',
            field=models.IntegerField(null=True),
        ),
    ]
