# Generated by Django 3.1.4 on 2021-01-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210127_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='content_duration_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='content_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='content_duration_unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='quantum_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='quantum_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='word_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='word_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
