# Generated by Django 3.1.4 on 2021-01-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_zohotoken'),
        ('projects', '0007_auto_20210127_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='must_have_domains',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='must_have_domains', to='admin_app.domain'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='nice_to_have_domain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.domain'),
        ),
    ]
