# Generated by Django 3.1.4 on 2021-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_zohotoken'),
        ('projects', '0008_auto_20210127_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='must_have_domains',
        ),
        migrations.AddField(
            model_name='requirement',
            name='must_have_domains',
            field=models.ManyToManyField(related_name='must_have_domains', to='admin_app.Domain'),
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='nice_to_have_domain',
        ),
        migrations.AddField(
            model_name='requirement',
            name='nice_to_have_domain',
            field=models.ManyToManyField(blank=True, to='admin_app.Domain'),
        ),
    ]
