# Generated by Django 3.1.4 on 2021-01-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210127_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherprojectdetail',
            name='compensation_from_client',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='otherprojectdetail',
            name='other_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='otherprojectdetail',
            name='phone_reimbursement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='otherprojectdetail',
            name='travel_expense_reimbursement',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
