# Generated by Django 3.1.4 on 2021-01-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_zohotoken'),
        ('projects', '0010_auto_20210127_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='admin_app.adminuser'),
        ),
        migrations.AddField(
            model_name='project',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(1, 'Proposed candidate salary'), (2, 'Propose project pricing to Client'), (3, 'Final client pricing'), (4, 'Final candidate salary')], default=1)),
                ('type_of_payout', models.CharField(choices=[('hourly', 'hourly'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='hourly', max_length=7)),
                ('min_salary', models.PositiveIntegerField(null=True)),
                ('max_salary', models.PositiveIntegerField(null=True)),
                ('project_duration_unit', models.CharField(max_length=10)),
                ('comments', models.TextField()),
                ('project_duration', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.adminuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
