# Generated by Django 3.1.4 on 2021-01-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210129_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexidetails',
            name='assignment_file',
            field=models.URLField(null=True),
        ),
    ]
