# Generated by Django 3.1.4 on 2021-01-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_zohotoken'),
        ('projects', '0014_auto_20210129_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexidetails',
            name='assignment_duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='must_have_domains',
            field=models.ManyToManyField(blank=True, related_name='must_have_domains', to='admin_app.Domain'),
        ),
    ]
