# Generated by Django 3.1.4 on 2021-01-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210129_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
