# Generated by Django 3.1.4 on 2021-01-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210129_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherprojectdetail',
            name='client_variable',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='otherprojectdetail',
            name='compensation_structure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='otherprojectdetail',
            name='existing_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='otherprojectdetail',
            name='when_make_it_known',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
