# Generated by Django 3.1.4 on 2021-01-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210129_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='detailed_job_description',
            field=models.TextField(blank=True),
        ),
    ]
