# Generated by Django 3.1.4 on 2021-01-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_requirement_detailed_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='language',
        ),
    ]
