# Generated by Django 3.1.4 on 2021-02-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_requirement_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexidetails',
            name='how_often_travelling',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
