# Generated by Django 3.1.4 on 2021-02-02 07:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_flexidetails_selected_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=None),
        ),
    ]
