# Generated by Django 3.1.4 on 2021-02-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20210202_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='language',
        ),
    ]
