# Generated by Django 3.1.4 on 2021-02-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_language'),
        ('projects', '0025_remove_requirement_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.language'),
        ),
    ]
