# Generated by Django 3.1.4 on 2021-02-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_language'),
        ('projects', '0026_requirement_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='language',
        ),
        migrations.AddField(
            model_name='requirement',
            name='language',
            field=models.ManyToManyField(blank=True, to='admin_app.Language'),
        ),
    ]
