# Generated by Django 3.1.4 on 2021-02-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20210202_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='content_duration_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
