# Generated by Django 3.1.4 on 2021-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20210202_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-modified', '-id')},
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='flexidetails',
            name='assignment_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Project Proposal'), (2, 'Project Details Updated'), (3, 'Candidate Salary Requested'), (4, 'Candidate Salary Proposed'), (5, 'Project Pricing to Client Updated'), (6, 'Project Details Updated'), (7, 'New'), (8, 'In Progress'), (9, 'Closed'), (10, 'Re-opened'), (11, 'Suspended'), (12, 'Final client pricing sent/received')], default=1),
        ),
    ]
