# Generated by Django 3.1.4 on 2021-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20210203_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexidetails',
            name='type_of_payout',
            field=models.CharField(choices=[('hourly', 'hourly'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='hourly', max_length=7),
        ),
        migrations.AddField(
            model_name='pricing',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='flexidetails',
            name='max_no_of_working_hours',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='flexidetails',
            name='min_no_of_working_hours',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AlterField(
            model_name='flexidetails',
            name='working_hours_duration_unit',
            field=models.CharField(blank=True, default='days', max_length=10),
        ),
    ]
