# Generated by Django 3.1.4 on 2021-02-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexidetails',
            name='turn_around_duration_unit',
            field=models.CharField(blank=True, default='weeks', max_length=10),
        ),
        migrations.AlterField(
            model_name='flexidetails',
            name='turn_around_time',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
