# Generated by Django 3.1.4 on 2021-02-12 09:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20210209_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='language',
        ),
        migrations.AddField(
            model_name='requirement',
            name='language',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
