# Generated by Django 3.1.4 on 2021-02-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20210212_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closed',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reopen',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suspended',
            name='reason',
            field=models.TextField(),
        ),
    ]
