# Generated by Django 3.1.4 on 2021-02-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20210215_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='own_contact_required',
            field=models.CharField(blank=True, default='No', max_length=50),
        ),
    ]
