# Generated by Django 3.1.4 on 2021-02-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20210216_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherprojectdetail',
            name='compensation_from_client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='otherprojectdetail',
            name='phone_reimbursement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='otherprojectdetail',
            name='travel_expense_reimbursement',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
