# Generated by Django 3.1.4 on 2021-02-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20210217_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexidetails',
            name='type_of_payout',
            field=models.CharField(choices=[('hourly', 'hourly'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='monthly', max_length=7),
        ),
    ]
