# Generated by Django 3.1.4 on 2021-02-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20210219_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notify_status',
            field=models.IntegerField(choices=[(1, 'Notification pending'), (2, 'Notified')], default=1),
        ),
    ]
