# Generated by Django 3.1.4 on 2021-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20210303_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recruitment_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
