# Generated by Django 3.1.4 on 2021-03-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_project_recruitment_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='max_total_experience_needed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='min_total_experience_needed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
