# Generated by Django 3.1.4 on 2021-03-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20210308_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reopen',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
