# Generated by Django 3.1.4 on 2021-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20210312_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='max_relevant_experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='min_relevant_experience',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
