# Generated by Django 3.1.4 on 2021-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20210312_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_selected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='flexifit_selected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
