# Generated by Django 3.1.4 on 2021-03-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20210316_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='flexifit_selected',
            new_name='flexibees_selected',
        ),
    ]
