# Generated by Django 3.1.4 on 2021-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20210316_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexidetails',
            name='type_of_payout',
            field=models.CharField(max_length=7),
        ),
    ]
