# Generated by Django 3.1.4 on 2021-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20210520_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='type_of_payout',
            field=models.CharField(max_length=100),
        ),
    ]
