# Generated by Django 3.1.4 on 2021-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20210727_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='model_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='role_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
