# Generated by Django 3.1.4 on 2022-01-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20210727_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='model_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='role_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
