# Generated by Django 3.1.4 on 2022-06-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_auto_20220121_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to_recruiter',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='send_to_bdmanager',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
