# Generated by Django 3.1.4 on 2023-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20220608_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assigned_to_recruiter',
            new_name='date_sent_to_recruitment',
        ),
        migrations.AddField(
            model_name='project',
            name='date_assigned_to_recruiter',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
