# Generated by Django 3.1.4 on 2024-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_auto_20230626_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='is_interview_required',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
