version: "3.8"

services:
  app:
    build: .
    container_name: dev-app-server
    restart: always
    ports:
      - "8000:8000"
    command: "gunicorn flexibees_finance.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/flexibees_finance/staticfiles

    depends_on:
      - redis

  redis:
    restart: always
    image: redis:latest
    container_name: redis-prod-server
    volumes:
      - redisdata:/data

volumes:
  redisdata:
  static_volume: {}  

