# Generated by Django 3.1.4 on 2024-11-04 06:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('common', '0001_initial'),
        ('candidate', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_contact_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Alternative Contact Person's Name")),
                ('alt_contact_person_number', models.CharField(blank=True, max_length=125, null=True, verbose_name="Alternative Contact Person's Phone")),
                ('alt_contact_person_relation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relation with Alternative Contact Person')),
                ('number_of_current_projects', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'status__in': ['17', '18', '19', '20', '21', '22', '23', '24', '25']}, on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to='candidate.candidate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.users')),
            ],
            options={
                'verbose_name': 'consultant',
                'verbose_name_plural': 'consultants',
                'db_table': 'finance_consultant',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_profile', models.URLField(blank=True, null=True, verbose_name='Facebook Profile URL')),
                ('instagram_profile', models.URLField(blank=True, null=True, verbose_name='Instagram Profile URL')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile URL')),
                ('twitter_profile', models.URLField(blank=True, null=True, verbose_name='Twitter Profile URL')),
                ('permit_social_media_tagging', models.BooleanField(default=False, verbose_name='Permit Social Media Tagging')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.users')),
            ],
            options={
                'verbose_name': 'social media',
                'verbose_name_plural': 'social medias',
                'db_table': 'finance_social_media',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_contract_type', models.CharField(choices=[('1', 'External Consultant'), ('2', 'Internal Consultant')], default='1', max_length=255, verbose_name='Consultant Contract Type')),
                ('client_contract_type', models.CharField(choices=[('1', 'International'), ('2', 'Domestic'), ('3', 'Placement')], default='1', max_length=255, verbose_name='Client Contract Type')),
                ('notice_period', models.IntegerField(verbose_name='Notice Period (in days)')),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('consultant_amount', models.IntegerField(verbose_name='Consultant Amount')),
                ('client_amount', models.IntegerField(verbose_name='Client Amount')),
                ('food_allowance', models.IntegerField(default=0, verbose_name='Food Allowance')),
                ('travel_allowance', models.IntegerField(default=0, verbose_name='Travel Allowance')),
                ('phone_allowance', models.IntegerField(default=0, verbose_name='Phone Allowance')),
                ('other_allowance', models.IntegerField(default=0, verbose_name='Other Allowance')),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'Published'), ('3', 'Pending Consultant Signature'), ('4', 'Pending Client Signature'), ('5', 'Signed'), ('6', 'In Progress'), ('7', 'Suspended'), ('8', 'Completed'), ('9', 'Pending Renewal'), ('10', 'Withdrawn')], default=1, max_length=125, verbose_name='Status')),
                ('pdf_link', models.URLField(blank=True, null=True, verbose_name='Link to Signed PDF')),
                ('digi_sign_link', models.URLField(blank=True, null=True, verbose_name='Digital Signature Link')),
                ('signatory_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Signatory Name')),
                ('signatory_designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authorized Signatory Designation')),
                ('signatory_image', models.ImageField(blank=True, null=True, upload_to='signaturs/images/', verbose_name='Signature')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.consultant')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.job')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'finance contract',
                'verbose_name_plural': 'finance contracts',
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='bank_documents/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='bank_documents/')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name="Account Holder's Name")),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=125, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=125, verbose_name='IFSC Code')),
                ('branch', models.CharField(max_length=255, verbose_name='Branch')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('bank_statement_or_cheque', models.FileField(blank=True, null=True, upload_to='bank_documents/')),
                ('account_type', models.CharField(max_length=125, verbose_name='Account Type')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.users')),
            ],
            options={
                'verbose_name': 'bank account',
                'verbose_name_plural': 'bank accounts',
                'db_table': 'finance_bank_account',
            },
        ),
    ]
