# Generated by Django 3.1.4 on 2024-10-25 13:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_profile', models.URLField(blank=True, null=True, verbose_name='Facebook Profile URL')),
                ('instagram_profile', models.URLField(blank=True, null=True, verbose_name='Instagram Profile URL')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile URL')),
                ('twitter_profile', models.URLField(blank=True, null=True, verbose_name='Twitter Profile URL')),
                ('permit_social_media_tagging', models.BooleanField(default=False, verbose_name='Permit Social Media Tagging')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.users')),
            ],
            options={
                'verbose_name': 'social media',
                'verbose_name_plural': 'social medias',
                'db_table': 'social media',
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_contact_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Alternative Contact Person's Name")),
                ('alt_contact_person_number', models.CharField(blank=True, max_length=125, null=True, verbose_name="Alternative Contact Person's Phone")),
                ('alt_contact_person_relation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relation with Alternative Contact Person')),
                ('number_of_projects', models.IntegerField()),
                ('number_of_current_projects', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'status': '17'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to='candidate.candidate')),
            ],
            options={
                'verbose_name': 'consultant',
                'verbose_name_plural': 'consultants',
                'db_table': 'consultant',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='bank_documents/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='bank_documents/')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name="Account Holder's Name")),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=125, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=125, verbose_name='IFSC Code')),
                ('branch', models.CharField(max_length=255, verbose_name='Branch')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('bank_statement_or_cheque', models.FileField(blank=True, null=True, upload_to='bank_documents/')),
                ('account_type', models.CharField(max_length=125, verbose_name='Account Type')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.users')),
            ],
            options={
                'verbose_name': 'bank detail',
                'verbose_name_plural': 'bank details',
                'db_table': 'bank detail',
            },
        ),
    ]
