# Generated by Django 3.1.4 on 2024-10-25 02:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0008_auto_20240822_0851'),
        ('projects', '0058_clientdetail_is_interview_required'),
        ('candidate', '0061_clientfeedback_attachment'),
        ('common', '0005_auto_20241025_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='bank_documents/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='bank_documents/')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name="Account Holder's Name")),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=125, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=125, verbose_name='IFSC Code')),
                ('branch', models.CharField(max_length=255, verbose_name='Branch')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('bank_statement_or_cheque', models.FileField(blank=True, null=True, upload_to='bank_documents/')),
                ('account_type', models.CharField(max_length=125, verbose_name='Account Type')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.users')),
            ],
            options={
                'verbose_name': 'bank detail',
                'verbose_name_plural': 'bank details',
                'db_table': 'bank detail',
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_contact_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Alternative Contact Person's Name")),
                ('alt_contact_person_number', models.CharField(blank=True, max_length=125, null=True, verbose_name="Alternative Contact Person's Phone")),
                ('alt_contact_person_relation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relation with Alternative Contact Person')),
                ('number_of_projects', models.IntegerField()),
                ('number_of_current_projects', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount')),
                ('candidate', models.ForeignKey(limit_choices_to={'status': '17'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to='candidate.candidate')),
            ],
            options={
                'verbose_name': 'consultant',
                'verbose_name_plural': 'consultants',
                'db_table': 'consultant',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_profile', models.URLField(blank=True, null=True, verbose_name='Facebook Profile URL')),
                ('instagram_profile', models.URLField(blank=True, null=True, verbose_name='Instagram Profile URL')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile URL')),
                ('twitter_profile', models.URLField(blank=True, null=True, verbose_name='Twitter Profile URL')),
                ('permit_social_media_tagging', models.BooleanField(default=False, verbose_name='Permit Social Media Tagging')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.users')),
            ],
            options={
                'verbose_name': 'social media',
                'verbose_name_plural': 'social medias',
                'db_table': 'social media',
            },
        ),
        migrations.CreateModel(
            name='ConsultantContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('1', 'Internal Consultant'), ('2', 'External Consultant'), ('3', 'Placement')], max_length=255, verbose_name='Domain')),
                ('notice_period', models.IntegerField(verbose_name='Notice Period (in days)')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Contract Date')),
                ('signed_date', models.DateField()),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('food_allowance', models.IntegerField(default=0, verbose_name='Food Allowance')),
                ('travel_allowance', models.IntegerField(default=0, verbose_name='Travel Allowance')),
                ('phone_allowance', models.IntegerField(default=0, verbose_name='Phone Allowance')),
                ('other_allowance', models.IntegerField(default=0, verbose_name='Other Allowance')),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'Shared'), ('3', 'Signed'), ('4', 'In Progress')], max_length=125, verbose_name='Status')),
                ('pdf_link', models.URLField(blank=True, null=True, verbose_name='Link to Signed PDF')),
                ('digi_sign_link', models.URLField(blank=True, null=True, verbose_name='Digital Signature Link')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.consultant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'db_table': 'contracts',
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='social_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.socialmedia'),
        ),
    ]
