# Generated by Django 3.1.4 on 2024-11-06 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='signatory_name',
        ),
        migrations.AddField(
            model_name='contract',
            name='bdm_gross_margin_commission_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='BDM Gross Margin Percentage'),
        ),
        migrations.AddField(
            model_name='contract',
            name='bdm_lifetime_commission_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='BDM Life Time Percentage'),
        ),
        migrations.AddField(
            model_name='contract',
            name='consultant_aggregate_amount',
            field=models.IntegerField(default=7000, verbose_name='Consultant Aggregate Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='client_contract_type',
            field=models.CharField(choices=[('1', 'International'), ('2', 'Domestic - Proprietorship'), ('3', 'Domestic - Non Proprietorship'), ('4', 'Placement - Full Time'), ('5', 'Placement - Part Time')], default='1', max_length=255, verbose_name='Client Contract Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='consultant_contract_type',
            field=models.CharField(choices=[('1', 'External Consultant'), ('2', 'Internal Consultant - BDM'), ('3', 'Internal Consultant - Other')], default='1', max_length=255, verbose_name='Consultant Contract Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employer.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='signatory_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/images/', verbose_name='Signature'),
        ),
    ]
