# Generated by Django 3.1.4 on 2024-10-25 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='number_of_current_projects',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='number_of_projects',
            field=models.IntegerField(default=1),
        ),
    ]
