# Generated by Django 3.1.4 on 2024-10-28 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('projects', '0001_initial'),
        ('finance', '0002_auto_20241025_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='number_of_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConsultantContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('1', 'Internal Consultant'), ('2', 'External Consultant'), ('3', 'Placement')], max_length=255, verbose_name='Domain')),
                ('notice_period', models.IntegerField(verbose_name='Notice Period (in days)')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Contract Date')),
                ('signed_date', models.DateField()),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('food_allowance', models.IntegerField(default=0, verbose_name='Food Allowance')),
                ('travel_allowance', models.IntegerField(default=0, verbose_name='Travel Allowance')),
                ('phone_allowance', models.IntegerField(default=0, verbose_name='Phone Allowance')),
                ('other_allowance', models.IntegerField(default=0, verbose_name='Other Allowance')),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'Shared'), ('3', 'Signed'), ('4', 'In Progress')], max_length=125, verbose_name='Status')),
                ('pdf_link', models.URLField(blank=True, null=True, verbose_name='Link to Signed PDF')),
                ('digi_sign_link', models.URLField(blank=True, null=True, verbose_name='Digital Signature Link')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.consultant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'db_table': 'contracts',
            },
        ),
    ]
