# Generated by Django 3.1.4 on 2024-11-07 04:42

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20241106_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='bank_documents/', validators=[apps.finance.models.validate_file_or_image]),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_statement_or_cheque',
            field=models.FileField(blank=True, null=True, upload_to='bank_documents/', validators=[apps.finance.models.validate_file_or_image]),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='bank_documents/', validators=[apps.finance.models.validate_file_or_image]),
        ),
    ]
