# Generated by Django 3.1.4 on 2024-10-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20241028_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantcontract',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultantcontract',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Shared'), ('3', 'Signed'), ('4', 'In Progress')], default=1, max_length=125, verbose_name='Status'),
        ),
    ]
