# Generated by Django 3.1.4 on 2024-11-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20241107_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='pan_card_number',
            field=models.CharField(default='GTD34E67', max_length=125, verbose_name='PAN Card Number'),
            preserve_default=False,
        ),
    ]
