# Generated by Django 3.1.4 on 2024-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_bankaccount_pan_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='director_name',
            field=models.CharField(choices=[('1', 'Shreya Prakash'), ('2', 'Reshmi RamMohan'), ('3', 'Internal Consultant - Other')], default='1', max_length=255, verbose_name='Director'),
        ),
    ]
