# Generated by Django 3.1.4 on 2024-10-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20241028_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantcontract',
            name='amount',
            field=models.IntegerField(default=10000, verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
