# Generated by Django 3.1.4 on 2024-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_contract_director_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='director_email',
            field=models.EmailField(default='director@email.com', max_length=254, verbose_name='Director email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='director_name',
            field=models.CharField(choices=[('1', 'Shreya Prakash'), ('2', 'Rashmi Rammohan'), ('3', 'Deepa Narayanaswamy')], default='1', max_length=255, verbose_name='Director'),
        ),
    ]
