# Generated by Django 3.1.4 on 2024-11-12 03:40

import apps.finance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('finance', '0006_auto_20241111_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_name', models.CharField(max_length=255, verbose_name='Legal Entity Name')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand Name (If any)')),
                ('date_of_incorporation', models.DateField(blank=True, null=True, verbose_name='Date of Incorporation')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('country', models.CharField(max_length=100, verbose_name='h. Country')),
                ('registered_under_gst_act', models.BooleanField(default=False, verbose_name='Whether Registered under GST Act 2017?')),
                ('type_of_registration', models.CharField(choices=[('1', 'Registered Business - Regular'), ('2', 'Consumer'), ('3', 'Overseas'), ('4', 'Registered Business - Composition'), ('5', 'Special Economic Zone'), ('6', 'SEZ Developer'), ('7', 'Tax Deductor'), ('8', 'Other')], default='1', max_length=255, verbose_name='Type of Registration')),
                ('gstin', models.CharField(blank=True, max_length=50, null=True, verbose_name='GSTIN')),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='gst_certificates/', validators=[apps.finance.models.validate_file_or_image])),
                ('registered_under_msmed', models.BooleanField(default=False, verbose_name='Whether Registered under MSMED?')),
                ('msme_registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='MSME Registration Number')),
                ('company_sector', models.CharField(choices=[('1', 'Agriculture'), ('2', 'Advertising & Marketing'), ('3', 'Analytics'), ('4', 'Apparel & Fashion'), ('5', 'Architecture & Planning'), ('6', 'Automobile Industry'), ('7', 'BPO / KPO / LPO'), ('8', 'Computer and Electronics Manufacturing'), ('9', 'Construction'), ('10', 'Consumer Discretionary /Luxury / Jewellery / Arts'), ('11', 'E-commerce'), ('12', 'EdTech / E-Learning'), ('13', 'Education'), ('14', 'Environmental Services /Sustainability / Renewable energy'), ('15', 'Event Management / Entertainment'), ('16', 'Financial Services'), ('17', 'FinTech'), ('18', 'FMCG / Food & Beverage'), ('19', 'Healthcare / Hospital management'), ('20', 'HealthTech'), ('1', 'HR / Recruitments'), ('2', 'Industrial Engineering / Automation'), ('3', 'Information Technology & Services'), ('4', 'Logistics & Supply Chain'), ('5', 'Management Consulting / Legal Services'), ('6', 'Manufacturing / Materials'), ('7', 'Non-profit'), ('8', 'Pharmaceuticals / Medical Related'), ('9', 'Property Management / Facility Service'), ('10', 'Publishing / Library / Book Shopss'), ('11', 'Real Estate'), ('12', 'Retail'), ('13', 'SAAS / PAAS'), ('14', 'Security'), ('15', 'Sports'), ('16', 'Tech / IT Consulting'), ('17', 'Telecommunication'), ('18', 'Travel / Tourism /Transport'), ('19', 'Utilities'), ('20', 'Venture Capital & Private Equity'), ('19', 'Wellness & Fitness'), ('20', 'Other')], default='1', max_length=255, verbose_name='Company Sector')),
                ('company_setup', models.CharField(choices=[('1', 'Start - up'), ('2', 'Small/Medium Enterprise'), ('3', 'Large Corporates'), ('4', 'Others')], default='1', max_length=255, verbose_name='Company Setup')),
                ('company_head_count', models.PositiveIntegerField(verbose_name='Company Head Count')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website/other source')),
                ('billing_currency', models.CharField(max_length=10, verbose_name='Billing Currency')),
                ('authorized_person_name', models.CharField(max_length=255, verbose_name='Name of authorized person for signing the contract')),
                ('authorized_person_designation', models.CharField(max_length=255, verbose_name='Designation of the authorized person')),
                ('authorized_person_email', models.EmailField(max_length=254, verbose_name='Mail id of the authorized person')),
                ('accounts_contact_person_name', models.CharField(max_length=255, verbose_name='Contact Person in Accounts/Finance Department')),
                ('accounts_contact_person_email', models.EmailField(max_length=254, verbose_name='Email Id of Accounts/Finance Person')),
                ('accounts_contact_person_phone', models.CharField(max_length=20, verbose_name='Phone no of Accounts/Finance Person')),
                ('send_hard_copy_invoice', models.BooleanField(default=False, verbose_name='Whether hard copy invoice to be sent for billing (by default we send soft copy only, but hard copy can be sent on request)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.socialmedia')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'clients',
            },
        ),
    ]
