# Generated by Django 3.1.4 on 2024-11-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='signatory_designation',
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.client'),
            preserve_default=False,
        ),
    ]
