# Generated by Django 3.1.4 on 2024-11-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20241112_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='consultant_contract_type',
            field=models.CharField(choices=[('1', 'External Consultant'), ('2', 'Internal Consultant - BDM'), ('3', 'Internal Consultant - Non BDM')], default='1', max_length=255, verbose_name='Consultant Contract Type'),
        ),
    ]
