# Generated by Django 3.1.4 on 2024-11-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20241113_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='working_days_in_a_week',
            field=models.IntegerField(default=5, verbose_name='Working days in a week'),
        ),
        migrations.AddField(
            model_name='contract',
            name='working_hours_per_day',
            field=models.IntegerField(default=8, verbose_name='Working hours per day'),
        ),
    ]
