# Generated by Django 3.1.4 on 2024-11-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20241113_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='paid_leaves',
            field=models.IntegerField(default=1, verbose_name='Number of paid leaves'),
        ),
    ]
