# Generated by Django 3.1.4 on 2024-11-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20241113_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='paid_leaves',
            field=models.IntegerField(default=6, verbose_name='Number of paid leaves'),
        ),
    ]
