# Generated by Django 3.1.4 on 2024-11-15 04:17

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20241113_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='bank_documents/', validators=[apps.finance.models.validate_file_or_image]),
        ),
        migrations.AddField(
            model_name='client',
            name='pan_card_number',
            field=models.CharField(default='GF34RT8Z', max_length=125, verbose_name='PAN Card Number'),
            preserve_default=False,
        ),
    ]
