# Generated by Django 3.1.4 on 2024-11-18 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20241115_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='initial_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of the consideration for the first installment (e.g., 70.00)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='initial_invoice_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of the first installment invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='second_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of the consideration for the second installment (e.g., 30.00)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='second_invoice_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of the first installment invoice'),
            preserve_default=False,
        ),
    ]
