# Generated by Django 3.1.4 on 2024-11-04 06:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('admin_priority', models.JSONField(blank=True, default={'afternoon': 'low', 'evening': 'low', 'morning': 'low', 'night': 'low'})),
                ('sessions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=50), size=None)),
                ('popularity_score', models.JSONField(blank=True, default={'afternoon': 0, 'evening': 0, 'morning': 0, 'night': 0})),
                ('free_time', models.BooleanField(default=False)),
                ('lifestyle_responses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1_a', 'Studying part time'), ('1_b', 'Studying full time'), ('1_c', 'Just graduated'), ('1_d', 'On a break'), ('1_e', 'Currently working full-time'), ('1_f', 'Currently working part-time'), ('1_g', 'Currently looking for work'), ('2_a', 'I live alone'), ('2_b', 'I live with friends'), ('2_c', 'I live in a nuclear family'), ('2_d', 'I live in a joint family'), ('3_2_c_a', 'I live with Parents'), ('3_2_c_b', 'I live with Spouse'), ('3_2_c_c', 'I live with Child'), ('3_2_c_d', 'I live with Spouse and Child'), ('3_e', 'I live with Others'), ('3_2_d_a', 'I live with Paternal/ Maternal Relatives'), ('3_2_d_b', 'I live with Spouse/ Maternal/ Paternal Relatives'), ('3_2_d_c', 'I live with Child / Maternal/ Paternal Relatives'), ('3_2_d_d', 'I live with Spouse and Child/ Maternal/ Paternal Relatives'), ('4_a', 'My-self'), ('4_b', 'Part time help'), ('4_c', 'Full time help'), ('4_d', 'Full time live-in-help')], max_length=50), blank=True, default=list, size=None)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('activity_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='availability.activitycard')),
            ],
        ),
    ]
