# Generated by Django 3.1.4 on 2021-05-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycard',
            name='popularity_score',
            field=models.JSONField(blank=True, default={'afternoon': 0, 'evening': 0, 'morning': 0, 'night': 0}),
        ),
    ]
