# Generated by Django 3.1.4 on 2024-10-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateavailability',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AddField(
            model_name='candidateavailability',
            name='next_activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='availability.candidateavailability'),
        ),
        migrations.AddField(
            model_name='candidateavailability',
            name='previous_activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='availability.candidateavailability'),
        ),
    ]
