# Generated by Django 3.1.4 on 2021-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_auto_20210521_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycard',
            name='free_time',
            field=models.BooleanField(default=False),
        ),
    ]
