# Generated by Django 3.1.4 on 2021-05-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_activitycard_free_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateavailability',
            name='next_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='availability.candidateavailability'),
        ),
        migrations.AddField(
            model_name='candidateavailability',
            name='previous_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='availability.candidateavailability'),
        ),
    ]
