# Generated by Django 3.1.4 on 2021-05-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0005_auto_20210525_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateavailability',
            name='next_activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='availability.candidateavailability'),
        ),
        migrations.AlterField(
            model_name='candidateavailability',
            name='previous_activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='availability.candidateavailability'),
        ),
    ]
