# Generated by Django 3.1.4 on 2024-11-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('common', '0001_initial'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Scheduled'), (2, 'In Review'), (3, 'Selected'), (4, 'Rejected'), (5, 'Position Filled Rejected')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate')),
            ],
            options={
                'db_table': 'candidate_job_status',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('website', models.URLField()),
                ('logo', models.URLField(null=True)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('1', '1 to 10'), ('2', '11 to 50'), ('3', '51 to 400'), ('4', '401 to 1000'), ('5', 'above 1000')], max_length=5)),
                ('target_audience', models.CharField(choices=[('1', 'B2B'), ('2', 'B2C'), ('3', 'others')], max_length=5)),
                ('source', models.CharField(choices=[('1', 'Social media'), ('2', 'Referral'), ('3', 'Search engines'), ('4', 'others')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_app.domain')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Employer Created'), ('2', 'Profile Related'), ('3', 'Created Job'), ('4', 'Selection in Progress'), ('5', 'Job in Progress'), ('6', 'Completed')], default='1', max_length=5)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employer.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.users')),
            ],
            options={
                'db_table': 'employers',
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interview_slots',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('1', 'Created'), ('2', 'Candidate Shortlisted'), ('3', 'Candidate Shown Interest'), ('4', 'Candidate Interview Scheduled'), ('5', 'Interview Cleared'), ('6', 'Finally Selected'), ('7', 'Project Confirmed'), ('8', 'Contract Pending'), ('9', 'Contract Pending from Client'), ('10', 'Contract Pending from Candidate'), ('11', 'Offered'), ('12', 'Accepted'), ('13', 'In Project'), ('14', 'Project Canceled'), ('15', 'Pending Renewal'), ('16', 'Withdrawn'), ('17', 'Dropped Off'), ('18', 'Termination'), ('19', 'Client in Limbo/Dropped Off')], default='1', max_length=5)),
                ('description', models.TextField()),
                ('flexi_details', models.JSONField(default={})),
                ('requirement_details', models.JSONField(default={})),
                ('other_details', models.JSONField(default={})),
                ('attachment', models.URLField(blank=True)),
                ('details', models.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.employer')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.function')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.role')),
                ('skills', models.ManyToManyField(related_name='job_skills', to='admin_app.Skill')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='SkippedCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.job')),
            ],
            options={
                'db_table': 'job_skipped_candidates',
            },
        ),
        migrations.CreateModel(
            name='RolesMinMaxPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.FloatField()),
                ('max_salary', models.FloatField()),
                ('currency', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.customrole')),
                ('existing_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.role')),
            ],
            options={
                'db_table': 'roles_min_max_pricing',
            },
        ),
        migrations.CreateModel(
            name='JobCustomRoleSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'pending'), ('2', 'approved'), ('3', 'rejected')], default='1', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.job')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.customrole')),
                ('skill', models.ManyToManyField(to='common.CustomSkill')),
            ],
            options={
                'db_table': 'job_custom_role_skills',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Scheduled'), ('2', 'Cleared'), ('3', 'Rejected')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.candidatejobstatus')),
                ('slots', models.ManyToManyField(to='employer.InterviewSlot')),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
        migrations.CreateModel(
            name='DraftJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Published')], default='1', max_length=2)),
                ('details', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.employer')),
            ],
            options={
                'db_table': 'draft_jobs',
            },
        ),
        migrations.AddField(
            model_name='candidatejobstatus',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.job'),
        ),
        migrations.CreateModel(
            name='CandidateJobNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.job')),
            ],
            options={
                'db_table': 'candidate_job_status_notes',
            },
        ),
    ]
