# Generated by Django 3.1.4 on 2024-06-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customskill',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rolemapping',
            name='function',
        ),
        migrations.RemoveField(
            model_name='rolemapping',
            name='role',
        ),
        migrations.RemoveField(
            model_name='skillmapping',
            name='role_mapping',
        ),
        migrations.RemoveField(
            model_name='skillmapping',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='users',
            name='type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='jobcustomroleskills',
            name='skill',
        ),
        migrations.AddField(
            model_name='employer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employer.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='attachment',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='flexi_details',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='job',
            name='other_details',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement_details',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='jobcustomroleskills',
            name='skills',
            field=models.ManyToManyField(to='common.CustomSkill'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.users'),
        ),
        migrations.AlterField(
            model_name='jobcustomroleskills',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.customrole'),
        ),
        migrations.DeleteModel(
            name='CustomRole',
        ),
        migrations.DeleteModel(
            name='CustomSkill',
        ),
        migrations.DeleteModel(
            name='RoleMapping',
        ),
        migrations.DeleteModel(
            name='SkillMapping',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
