# Generated by Django 3.1.4 on 2024-07-19 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_auto_20231009_1217'),
        ('common', '0001_initial'),
        ('employer', '0003_auto_20240624_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesMinMaxPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.FloatField()),
                ('max_salary', models.FloatField()),
                ('currency', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.customrole')),
                ('existing_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.role')),
            ],
            options={
                'db_table': 'roles_min_max_pricing',
            },
        ),
    ]
