# Generated by Django 3.1.4 on 2024-08-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0059_candidate_status'),
        ('employer', '0004_rolesminmaxpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Scheduled'), (2, 'In Review'), (3, 'Selected'), (4, 'Rejected')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.job')),
            ],
            options={
                'db_table': 'candidate_job_status',
            },
        ),
        migrations.CreateModel(
            name='SkippedCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.job')),
            ],
            options={
                'db_table': 'job_skipped_candidates',
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Rejected')], max_length=5)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.candidatejobstatus')),
            ],
            options={
                'db_table': 'interviews_feedback',
            },
        ),
        migrations.CreateModel(
            name='EmployerInterviewSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.candidatejobstatus')),
            ],
            options={
                'db_table': 'employer_interview_slots',
            },
        ),
        migrations.CreateModel(
            name='CandidateJobNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.job')),
            ],
            options={
                'db_table': 'candidate_job_status_notes',
            },
        ),
    ]
