# Generated by Django 3.1.4 on 2024-08-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_auto_20240809_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[('1', 'Scheduled'), ('2', 'Cleared'), ('3', 'Rejected')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interview_slots',
            },
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='candidate_job_status',
        ),
        migrations.AlterField(
            model_name='candidatejobstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Scheduled'), (2, 'In Review'), (3, 'Selected'), (4, 'Rejected'), (5, 'Position Filled Rejected')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Created'), ('2', 'Candidate Shortlisted'), ('3', 'Candidate Shown Interest'), ('4', 'Candidate Interview Scheduled'), ('5', 'Interview Cleared'), ('6', 'Finally Selected'), ('7', 'Project Confirmed'), ('8', 'Contract Pending'), ('9', 'Contract Pending from Client'), ('10', 'Contract Pending from Candidate'), ('11', 'Offered'), ('12', 'Accepted'), ('13', 'In Project'), ('14', 'Project Canceled'), ('15', 'Pending Renewal'), ('16', 'Withdrawn'), ('17', 'Dropped Off'), ('18', 'Termination'), ('19', 'Client in Limbo/Dropped Off')], default='1', max_length=5),
        ),
        migrations.DeleteModel(
            name='EmployerInterviewSlot',
        ),
        migrations.DeleteModel(
            name='InterviewFeedback',
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.candidatejobstatus'),
        ),
        migrations.AddField(
            model_name='interview',
            name='slots',
            field=models.ManyToManyField(to='employer.InterviewSlot'),
        ),
    ]
