LINE_BREAK = "info || ************************ | LINE BREAK | ************************"
DATE_FORMAT_STR ="%d-%m-%Y"
BLANK = ''
SIGNUP = 'Employer signup'
SIGNIN = 'Employer login'
VERIFY_OTP = 'Employer verify otp'
PROFILE_UPDATE = 'Employer update profile'
MOBILE_CHANGE = 'Employer mobile change'
GET_PROFILE = 'Employer get profile'
LOGOUT = 'Employer logout'
JOB_CREATION_FUNCTION = 'Employer job ceation function list'
JOB_CREATION_ROLE = 'Employer job ceation roles list'
JOB_CREATION_SKILLS = 'Employer job ceation skills list'
JOB_DESCRIPTION_GENERATOR = 'EmployerJob description Generator'
DOMAIN_LIST = 'Employer domain list'
CANDIDATE_RECOMMENDATION = 'Employer candidate recommendation list'
DRAFT_JOB_CREATE_UPDATE = 'Draft job'
DRAFT_JOB_RETRIVE = 'Draft job retrive'
DRAFT_JOB_DELETE = 'Draft job delete'
DRAFT_JOB_LIST = 'Draft job list'
JOB_CREATION = 'Job creation'
ROLE_LISTING_VIEWER = 'Role Listing Viewer'
CUSTOM_ROLE_APPROVAL = 'Custom role approval status update'
UPDATE_ROLE_NAME = 'Update role name'
UPDATE_SKILL_NAME = 'Update skill name'
ROLE_SKILLS_LISTING = 'Roles and skills listing'
DEACTIVATE = 'Deactivate'
JOB_DESC_GENERATOR_FAILED = "Sorry we are unable to generate job description"
ASSET_UPLOAD = 'Asset upload'
JOB_LISTING = 'Jobs listing'
JOBS_HOME_LISTING = 'Jobs home listing'
JOB_DYNAMIC_QUESTION = 'Employer job dynamic questions list'
MATCHING_CANDIDATES_LIST = 'matching candidates list'
PRICING_INTEGRATION_IN_JOB = 'Pricing integration in job'
INDIVIDUAL_JOB_DETAILS = 'Individual job details'
INDIVIDUAL_JOB_DETAILS_STATUS = "Sub Function status update"
SKIP_CANDIDATE = 'Skip candidate'
SHORTLIST_CANDIDATE = 'Shortlist candidate'
EMPLOYER_CANDIDATES_NOTES = 'Please provide correct field'
EMPLOYER_CANDIDATES_NOTES_API = 'Employer candidate notes api'
EMPLOYER_TIME_SLOT_INTERVIEW = 'Employer time slot interview'
GET_SHORTLIST_CANDIDATES = 'Get shortlist candidates'
UPDATE_FEEDBACK = 'Update feedback'
SUPPORT = 'Employer support'
EMPLOYER_SLOT_DAYS_ERROR = "Only five working day allowed"
EMPLOYER_SLOT_TIME_COLLISION = "Time slot has collision with existing slots with same date and times"
EMPLOYER_SLOT_TIME_FORMAT_ERROR = "Incorrect date or time format. Please use 'YYYY-MM-DD' for date and 'HH:MM:SS' for time."
MAX_EMPLOYER_SLOT_TIME_PER_DAY = "Time slot cannot be more than {} in a day"
EMPLOYER_SLOT_EXISTING_COUNT= "You already have an existing {} slot on this date ,You can select {} more slot on the same date"
UNABLE_TO_FIND_FEEDBACK = "Feedback not found"
VIEW_FEEDBACK_IDS = "Please provide job_id and candidate_id"
PROJECT_ALL_CADNDIDATES_LIST = "Projects all candidates listing"
