# Generated by Django 3.1.4 on 2024-10-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('employer', '0001_initial'),
        ('admin_app', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='job_interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.interview'),
        ),
        migrations.AddField(
            model_name='certification',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AddField(
            model_name='candidatelanguage',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AddField(
            model_name='candidatelanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.language'),
        ),
        migrations.AddField(
            model_name='candidateattachment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='roles',
            field=models.ManyToManyField(blank=True, to='admin_app.Role'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(blank=True, to='admin_app.Skill'),
        ),
        migrations.AddField(
            model_name='assignmentfeedback',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentfeedback',
            name='feedback_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.adminuser'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
