# Generated by Django 3.1.4 on 2021-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20210224_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hire',
            field=models.BooleanField(default=True),
        ),
    ]
