# Generated by Django 3.1.4 on 2021-03-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='years_of_break',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
