# Generated by Django 3.1.4 on 2021-03-01 18:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidate_years_of_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='relevant_experiences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
