# Generated by Django 3.1.4 on 2021-03-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidate_relevant_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='relevant_experiences',
            field=models.JSONField(blank=True),
        ),
    ]
