# Generated by Django 3.1.4 on 2021-03-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20210302_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='relevant_experiences',
            new_name='relevantexp',
        ),
    ]
