# Generated by Django 3.1.4 on 2021-03-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20210302_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='relevantexp',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
