# Generated by Django 3.1.4 on 2021-03-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20210303_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexifit',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flexifit',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='functional',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='functional',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
