# Generated by Django 3.1.4 on 2021-03-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20210312_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentfeedback',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='clientfeedback',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='flexifitfeedback',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='functionalfeedback',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='candidate',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
