# Generated by Django 3.1.4 on 2021-03-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_auto_20210315_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentfeedback',
            name='recommendation',
            field=models.IntegerField(choices=[(3, 'Assignment not cleared'), (4, 'Assignment cleared'), (5, 'Assignment on hold')], default=3),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='recommendation',
            field=models.IntegerField(choices=[(3, 'Client selected'), (4, 'Client rejected')], default=4),
        ),
        migrations.AddField(
            model_name='flexifitfeedback',
            name='recommendation',
            field=models.IntegerField(choices=[(2, 'Candidate selected'), (3, 'Candidate not selected'), (4, 'Flexifit on hold')], default=3),
        ),
        migrations.AddField(
            model_name='functionalfeedback',
            name='recommendation',
            field=models.IntegerField(choices=[(2, 'Functional interview cleared'), (3, 'Functional interview not cleared'), (4, 'Functional on hold')], default=3),
        ),
    ]
