# Generated by Django 3.1.4 on 2021-03-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_auto_20210315_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_link',
            field=models.URLField(null=True),
        ),
    ]
