# Generated by Django 3.1.4 on 2021-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_auto_20210319_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='legacy_skills',
            field=models.TextField(blank=True),
        ),
    ]
