# Generated by Django 3.1.4 on 2021-03-26 09:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_auto_20210326_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexifitfeedback',
            name='interview_summary',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
