# Generated by Django 3.1.4 on 2021-04-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_auto_20210326_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
