# Generated by Django 3.1.4 on 2021-04-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_auto_20210405_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='legacy_last_employer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='legacy_last_role',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='legacy_prior_employers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='legacy_prior_roles',
            field=models.TextField(blank=True),
        ),
    ]
