# Generated by Django 3.1.4 on 2021-04-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_auto_20210405_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentdetail',
            name='employment_type',
        ),
    ]
