# Generated by Django 3.1.4 on 2021-04-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_employmentdetail_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentdetail',
            name='employment_type',
        ),
    ]
