# Generated by Django 3.1.4 on 2021-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_remove_employmentdetail_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdetail',
            name='employment_type',
            field=models.CharField(choices=[('Full Time Employee', 'Full Time Employee'), ('Full Time Contractor', 'Full Time Contractor'), ('Part Time Employee', 'Part Time Employee'), ('Part Time Contractor', 'Part Time Contractor'), ('Consultant', 'Consultant'), ('Paid Internship', 'Paid Internship'), ('Unpaid Internship', 'Unpaid Internship')], default='Full Time Employee', max_length=50),
        ),
    ]
