# Generated by Django 3.1.4 on 2021-04-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0026_auto_20210408_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='otp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
