# Generated by Django 3.1.4 on 2021-04-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_auto_20210409_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='issue_date',
            field=models.PositiveIntegerField(default=2010),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.PositiveIntegerField(default=2010),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.PositiveIntegerField(default=2010),
            preserve_default=False,
        ),
    ]
