# Generated by Django 3.1.4 on 2021-04-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0029_auto_20210409_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatelanguage',
            name='proficiency',
        ),
    ]
