# Generated by Django 3.1.4 on 2021-04-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0031_candidatelanguage_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatelanguage',
            name='proficiency',
        ),
    ]
