# Generated by Django 3.1.4 on 2021-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0032_remove_candidatelanguage_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatelanguage',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=20),
        ),
    ]
