# Generated by Django 3.1.4 on 2021-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0033_candidatelanguage_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateattachment',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
