# Generated by Django 3.1.4 on 2021-04-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0034_candidateattachment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassessment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='selfassessment',
            name='skill',
        ),
    ]
