# Generated by Django 3.1.4 on 2021-04-21 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0035_auto_20210415_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='read_notifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), blank=True, default=list, size=None),
        ),
    ]
