# Generated by Django 3.1.4 on 2021-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0037_candidate_hear_about_detailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='total_year_of_experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_of_break',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
