# Generated by Django 3.1.4 on 2021-05-18 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0038_auto_20210504_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='lifestyle_responses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='candidate',
            name='questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='timeline_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='timeline_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_available_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='wakeup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
