# Generated by Django 3.1.4 on 2021-05-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0040_auto_20210520_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mylife_last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
