# Generated by Django 3.1.4 on 2021-06-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0042_candidate_profile_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='total_year_of_experience',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_of_break',
            field=models.FloatField(default=0.0),
        ),
    ]
