# Generated by Django 3.1.4 on 2021-07-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0044_auto_20210630_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='recommendation',
            field=models.IntegerField(choices=[(3, 'Client selected'), (4, 'Client rejected'), (5, 'Partial selected')], default=4),
        ),
        migrations.AlterField(
            model_name='finalselection',
            name='status',
            field=models.IntegerField(choices=[(1, 'Flexibees selected'), (2, 'Sent to BD manager'), (3, 'Client selected'), (4, 'Client rejected'), (5, 'Partial selected')], default=1),
        ),
    ]
