# Generated by Django 3.1.4 on 2021-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0045_auto_20210708_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalselection',
            name='status',
            field=models.IntegerField(choices=[(1, 'Flexibees selected'), (2, 'Sent to BD manager'), (3, 'Client selected'), (4, 'Client rejected'), (5, 'Partial selected'), (6, 'Selected')], default=1),
        ),
    ]
