# Generated by Django 3.1.4 on 2021-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0046_auto_20210712_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='flexibees_selected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
