# Generated by Django 3.1.4 on 2021-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0047_candidate_flexibees_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalselection',
            name='recruiter_comments',
            field=models.TextField(blank=True),
        ),
    ]
