# Generated by Django 3.1.4 on 2021-07-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0048_finalselection_recruiter_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalselection',
            name='recruiter_comments',
            field=models.TextField(),
        ),
    ]
