# Generated by Django 3.1.4 on 2022-06-06 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0049_auto_20210719_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills_resume',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, size=None),
        ),
    ]
