# Generated by Django 3.1.4 on 2022-07-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0050_candidate_skills_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalselection',
            name='send_to_bdmanager',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
