# Generated by Django 3.1.4 on 2022-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0051_finalselection_send_to_bdmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='last_used_andriod_app_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_used_ios_app_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
