# Generated by Django 3.1.4 on 2023-01-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0052_auto_20220907_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalselection',
            name='final_notification_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
