# Generated by Django 3.1.4 on 2023-03-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0053_finalselection_final_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='functional',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='functional',
            name='no_of_notifications_on_my_typical_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
