# Generated by Django 3.1.4 on 2023-04-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0054_auto_20230321_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='last_notified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notification_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
