# Generated by Django 3.1.4 on 2023-05-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0055_auto_20230419_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='previous_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
