# Generated by Django 3.1.4 on 2023-07-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0056_candidate_previous_email'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX idx_phone ON candidate_candidate (phone);",
            "DROP INDEX idx_phone;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_email ON candidate_candidate (email);",
            "DROP INDEX idx_email;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_first_name ON candidate_candidate (first_name);",
            "DROP INDEX idx_first_name;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_last_name ON candidate_candidate (last_name);",
            "DROP INDEX idx_last_name;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_active_projects ON candidate_candidate (active_projects);",
            "DROP INDEX idx_active_projects;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_total_available_hours ON candidate_candidate (total_available_hours);",
            "DROP INDEX idx_total_available_hours;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_flexibees_selected ON candidate_candidate (flexibees_selected);",
            "DROP INDEX idx_flexibees_selected;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_total_year_of_experience ON candidate_candidate (total_year_of_experience);",
            "DROP INDEX idx_total_year_of_experience;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_relevantexp ON candidate_candidate (relevantexp);",
            "DROP INDEX idx_relevantexp;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_active ON candidate_candidate (active);",
            "DROP INDEX idx_active;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_city ON candidate_candidate (city);",
            "DROP INDEX idx_city;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_hire ON candidate_candidate (hire);",
            "DROP INDEX idx_hire;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_skills_resume ON candidate_candidate (skills_resume);",
            "DROP INDEX idx_skills_resume;",
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_company ON candidate_employmentdetail (company);",
            "DROP INDEX idx_company;",
        ),
    ]
