# Generated by Django 3.1.4 on 2024-08-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0058_emailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('1', 'Signed Up'), ('2', 'Profile Completed'), ('3', 'Ready For Functional'), ('4', 'Functional Interview Scheduled'), ('5', 'Functional Interview Completed'), ('6', 'Functional Interview Failed'), ('7', 'Ready For Flexifit'), ('8', 'Flexifit Scheduled'), ('9', 'Flexifit Interview Failed'), ('10', 'Flexifit Completed'), ('11', 'Ready for Client'), ('12', 'Job Ready'), ('13', 'Job Interested'), ('14', 'Client Interview Scheduled'), ('15', 'Client Interview Completed'), ('16', 'Project Selected'), ('17', 'Project Confirmed'), ('18', 'Offered'), ('19', 'Accepted'), ('20', 'Project Started'), ('21', 'Project In Progress'), ('22', 'Project Suspended'), ('23', 'Project Completed'), ('24', 'Dormant'), ('25', 'Unsubscribe/Delete')], max_length=3, null=True),
        ),
    ]
