# Generated by Django 3.1.4 on 2024-08-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0060_auto_20240821_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='attachment',
            field=models.URLField(null=True),
        ),
    ]
