# Generated by Django 3.1.4 on 2024-10-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('common', '0001_initial'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customskill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.employer'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.employer'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_app.function'),
        ),
        migrations.AddIndex(
            model_name='customskill',
            index=models.Index(fields=['skill_name'], name='idx_custom_skill_names'),
        ),
        migrations.AddIndex(
            model_name='customrole',
            index=models.Index(fields=['role_name'], name='idx_custom_role_names'),
        ),
    ]
