# Generated by Django 3.1.4 on 2024-09-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20240730_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemapping',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
