# Generated by Django 3.1.4 on 2021-02-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0017_dropdown_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('project', 'project'), ('candidate', 'candidate')], default='project', max_length=10)),
                ('item_id', models.PositiveIntegerField()),
                ('sent_by_type', models.CharField(choices=[('bd', 'BD'), ('admin', 'Recruiter Admin'), ('recruiter', 'Recruiter'), ('sme', 'SME'), ('super_admin', 'Super Admin'), ('candidate', 'Candidate')], max_length=15)),
                ('sent_to_type', models.CharField(choices=[('bd', 'BD'), ('admin', 'Recruiter Admin'), ('recruiter', 'Recruiter'), ('sme', 'SME'), ('super_admin', 'Super Admin'), ('candidate', 'Candidate')], max_length=15)),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to='admin_app.adminuser')),
                ('sent_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.adminuser')),
            ],
        ),
    ]
