# Generated by Django 3.1.4 on 2021-03-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_auto_20210319_0524'),
        ('admin_app', '0019_adminuser_active_projects'),
        ('notifications', '0002_auto_20210211_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('project', 'project'), ('candidate', 'candidate')], default='project', max_length=10)),
                ('item_id', models.PositiveIntegerField()),
                ('all', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sent_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.adminuser')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
