# Generated by Django 3.1.4 on 2021-03-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_candidate_active_projects'),
        ('notifications', '0003_candidatenotification_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatenotification',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
    ]
